/**
 * Static demo seed definitions — imported by scripts/seed-demo.ts
 */

export const DEMO_PASSWORD = "GridLinkDemo2026!"

export const BUYERS = [
  {
    email: "procurement@mercy-health-demo.example.com",
    fullName: "Sarah Chen",
    companyName: "Mercy Regional Health System",
    orgName: "Mercy Regional Health System",
    industry: "Healthcare",
  },
  {
    email: "fuel@cityworks-demo.example.com",
    fullName: "James Okonkwo",
    companyName: "City of Lakewood Public Works",
    orgName: "City of Lakewood Public Works",
    industry: "Municipal Government",
  },
  {
    email: "fleet.fuel@continental-logistics-demo.example.com",
    fullName: "Maria Santos",
    companyName: "Continental Logistics Group",
    orgName: "Continental Logistics Group",
    industry: "Transportation & Logistics",
  },
  {
    email: "energy@northstar-foods-demo.example.com",
    fullName: "David Park",
    companyName: "NorthStar Foods Manufacturing",
    orgName: "NorthStar Foods Manufacturing",
    industry: "Food & Beverage Manufacturing",
  },
  {
    email: "fuel.services@metro-airport-demo.example.com",
    fullName: "Elena Vasquez",
    companyName: "Metro International Airport Authority",
    orgName: "Metro International Airport Authority",
    industry: "Aviation",
  },
] as const

/** 30 verified vendors — ids v1000001-0001-4001-8001-000000000001 … 030 */
export const VENDOR_DEFS = [
  {
    slug: "midwest-petroleum",
    companyName: "Midwest Petroleum Group",
    stateInc: "Illinois",
    nationwide: true,
    states: ["Illinois", "Indiana", "Wisconsin", "Iowa", "Missouri", "Minnesota", "Ohio", "Michigan"],
    annualGallons: 185_000_000,
    cert: "DBE" as const,
    products: ["Diesel", "Gas", "Premium Gas", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 42,
    transports: 68,
    rep: { first: "Marcus", last: "Reilly", email: "marcus.reilly@midwest-petroleum.example.com" },
  },
  {
    slug: "cascade-fuel",
    companyName: "Cascade Fuel Services",
    stateInc: "Washington",
    nationwide: false,
    states: ["Washington", "Oregon", "Idaho"],
    annualGallons: 72_000_000,
    cert: "WBE" as const,
    products: ["Diesel", "Gas", "Heating Oil", "DEF"],
    wetHose: true,
    emergency: "Under 2 hours",
    tankwagons: 18,
    transports: 24,
    rep: { first: "Jennifer", last: "Walsh", email: "j.walsh@cascade-fuel.example.com" },
  },
  {
    slug: "southern-gulf",
    companyName: "Southern Gulf Distributors",
    stateInc: "Texas",
    nationwide: false,
    states: ["Texas", "Louisiana", "Oklahoma", "Arkansas", "Mississippi", "Alabama"],
    annualGallons: 220_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Dyed Diesel", "Marine Fuel"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 55,
    transports: 90,
    rep: { first: "Robert", last: "Hale", email: "rhale@southern-gulf.example.com" },
  },
  {
    slug: "mountain-states",
    companyName: "Mountain States Energy",
    stateInc: "Colorado",
    nationwide: false,
    states: ["Colorado", "Wyoming", "Montana", "Utah", "New Mexico"],
    annualGallons: 48_000_000,
    cert: "Veteran-Owned" as const,
    products: ["Diesel", "Gas", "Propane", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 14,
    transports: 22,
    rep: { first: "Tyler", last: "Brooks", email: "tbrooks@mountain-states.example.com" },
  },
  {
    slug: "northeast-fuel",
    companyName: "Northeast Fuel Logistics",
    stateInc: "Massachusetts",
    nationwide: false,
    states: ["Massachusetts", "New Hampshire", "Vermont", "Maine", "Rhode Island", "Connecticut", "New York", "New Jersey"],
    annualGallons: 95_000_000,
    cert: "DBE" as const,
    products: ["Diesel", "Gas", "Premium Gas", "Heating Oil", "DEF"],
    wetHose: true,
    emergency: "Under 24 hours",
    tankwagons: 28,
    transports: 35,
    rep: { first: "Patricia", last: "Nguyen", email: "pnguyen@northeast-fuel.example.com" },
  },
  {
    slug: "pacific-coast",
    companyName: "Pacific Coast Petroleum",
    stateInc: "California",
    nationwide: true,
    states: ["California", "Nevada", "Arizona", "Oregon", "Washington"],
    annualGallons: 250_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Renewable Fuel", "Bio-Diesel", "DEF"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 60,
    transports: 85,
    rep: { first: "Andrew", last: "Kim", email: "akim@pacific-coast-petroleum.example.com" },
  },
  {
    slug: "heartland-energy",
    companyName: "Heartland Energy Partners",
    stateInc: "Iowa",
    nationwide: false,
    states: ["Iowa", "Nebraska", "South Dakota", "Minnesota"],
    annualGallons: 38_000_000,
    cert: "HUBZone" as const,
    products: ["Diesel", "Gas", "Dyed Diesel", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 12,
    transports: 18,
    rep: { first: "Lisa", last: "Hoffman", email: "lisa.hoffman@heartland-energy.example.com" },
  },
  {
    slug: "gulfstream",
    companyName: "Gulfstream Fuels",
    stateInc: "Florida",
    nationwide: false,
    states: ["Florida", "Georgia", "South Carolina"],
    annualGallons: 62_000_000,
    cert: "WBE" as const,
    products: ["Diesel", "Gas", "Marine Fuel", "DEF"],
    wetHose: true,
    emergency: "Under 2 hours",
    tankwagons: 20,
    transports: 30,
    rep: { first: "Carlos", last: "Mendez", email: "cmendez@gulfstream-fuels.example.com" },
  },
  {
    slug: "prairie-states",
    companyName: "Prairie States Petroleum",
    stateInc: "Kansas",
    nationwide: false,
    states: ["Kansas"],
    annualGallons: 8_500_000,
    cert: null,
    products: ["Diesel", "Gas", "Propane"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 6,
    transports: 8,
    rep: { first: "Brian", last: "Fischer", email: "bfischer@prairie-states.example.com" },
  },
  {
    slug: "summit-petroleum",
    companyName: "Summit Petroleum LLC",
    stateInc: "Minnesota",
    nationwide: false,
    states: ["Minnesota", "Wisconsin", "North Dakota"],
    annualGallons: 28_000_000,
    cert: "DBE" as const,
    products: ["Diesel", "Gas", "DEF", "Heating Oil"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 10,
    transports: 16,
    rep: { first: "Karen", last: "Larson", email: "klarson@summit-petroleum.example.com" },
  },
  {
    slug: "lakefront-fuel",
    companyName: "Lakefront Fuel Services",
    stateInc: "Michigan",
    nationwide: false,
    states: ["Michigan", "Ohio", "Indiana"],
    annualGallons: 41_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Premium Gas"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 15,
    transports: 20,
    rep: { first: "Michael", last: "Torres", email: "mtorres@lakefront-fuel.example.com" },
  },
  {
    slug: "delta-transport",
    companyName: "Delta Fuel Transport",
    stateInc: "Tennessee",
    nationwide: false,
    states: ["Tennessee", "Kentucky", "Alabama", "Mississippi"],
    annualGallons: 55_000_000,
    cert: "Veteran-Owned" as const,
    products: ["Diesel", "Dyed Diesel", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 18,
    transports: 28,
    rep: { first: "Diane", last: "Carter", email: "dcarter@delta-transport.example.com" },
  },
  {
    slug: "keystone",
    companyName: "Keystone Petroleum LLC",
    stateInc: "Pennsylvania",
    nationwide: false,
    states: ["Pennsylvania", "Ohio", "West Virginia", "Maryland", "Delaware"],
    annualGallons: 67_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Heating Oil", "DEF"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 22,
    transports: 32,
    rep: { first: "Steven", last: "Brennan", email: "sbrennan@keystone-petroleum.example.com" },
  },
  {
    slug: "bayou-fuel",
    companyName: "Bayou Fuel Partners",
    stateInc: "Louisiana",
    nationwide: false,
    states: ["Louisiana", "Texas"],
    annualGallons: 33_000_000,
    cert: "WBE" as const,
    products: ["Diesel", "Marine Fuel", "Gas"],
    wetHose: true,
    emergency: "Under 2 hours",
    tankwagons: 11,
    transports: 19,
    rep: { first: "Renee", last: "Boudreaux", email: "rboudreaux@bayou-fuel.example.com" },
  },
  {
    slug: "vanguard",
    companyName: "Vanguard Fuels",
    stateInc: "Virginia",
    nationwide: true,
    states: ["Virginia", "North Carolina", "South Carolina", "Maryland", "Georgia", "Tennessee"],
    annualGallons: 142_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Premium Gas", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 38,
    transports: 52,
    rep: { first: "Gregory", last: "Shaw", email: "gshaw@vanguard-fuels.example.com" },
  },
  {
    slug: "sterling",
    companyName: "Sterling Fuel Group",
    stateInc: "New York",
    nationwide: false,
    states: ["New York"],
    annualGallons: 12_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Heating Oil"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 8,
    transports: 10,
    rep: { first: "Angela", last: "Russo", email: "arusso@sterling-fuel.example.com" },
  },
  {
    slug: "meridian",
    companyName: "Meridian Fuels",
    stateInc: "North Carolina",
    nationwide: false,
    states: ["North Carolina", "Virginia", "South Carolina"],
    annualGallons: 24_000_000,
    cert: "HUBZone" as const,
    products: ["Diesel", "Gas", "DEF"],
    wetHose: true,
    emergency: "Under 8 hours",
    tankwagons: 9,
    transports: 14,
    rep: { first: "William", last: "Pierce", email: "wpierce@meridian-fuels.example.com" },
  },
  {
    slug: "pioneer",
    companyName: "Pioneer Fuel Co.",
    stateInc: "Oklahoma",
    nationwide: false,
    states: ["Oklahoma", "Kansas", "Texas", "Arkansas"],
    annualGallons: 19_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Propane"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 7,
    transports: 12,
    rep: { first: "Laura", last: "Whitfield", email: "lwhitfield@pioneer-fuel.example.com" },
  },
  {
    slug: "western-states",
    companyName: "Western States Petroleum",
    stateInc: "Arizona",
    nationwide: false,
    states: ["Arizona", "New Mexico", "Nevada", "Utah"],
    annualGallons: 44_000_000,
    cert: "DBE" as const,
    products: ["Diesel", "Gas", "DEF"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 16,
    transports: 22,
    rep: { first: "Jason", last: "Morales", email: "jmorales@western-states.example.com" },
  },
  {
    slug: "sunbelt",
    companyName: "Sunbelt Petroleum Group",
    stateInc: "Georgia",
    nationwide: false,
    states: ["Georgia", "Florida", "Alabama", "South Carolina", "North Carolina", "Tennessee"],
    annualGallons: 198_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Premium Gas", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 48,
    transports: 70,
    rep: { first: "Christine", last: "Davis", email: "cdavis@sunbelt-petroleum.example.com" },
  },
  {
    slug: "harbor-city",
    companyName: "Harbor City Petroleum",
    stateInc: "Maryland",
    nationwide: false,
    states: ["Maryland", "Virginia", "Delaware", "Pennsylvania", "New Jersey"],
    annualGallons: 36_000_000,
    cert: null,
    products: ["Diesel", "Marine Fuel", "Gas", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 13,
    transports: 17,
    rep: { first: "Thomas", last: "Greene", email: "tgreene@harbor-city.example.com" },
  },
  {
    slug: "iron-range",
    companyName: "Iron Range Oil & Gas",
    stateInc: "Minnesota",
    nationwide: false,
    states: ["Minnesota", "Wisconsin"],
    annualGallons: 6_200_000,
    cert: null,
    products: ["Diesel", "Heating Oil", "Gas"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 5,
    transports: 6,
    rep: { first: "Heather", last: "Nordstrom", email: "hnordstrom@iron-range.example.com" },
  },
  {
    slug: "coastal-energy",
    companyName: "Coastal Energy Logistics",
    stateInc: "California",
    nationwide: false,
    states: ["California", "Oregon"],
    annualGallons: 58_000_000,
    cert: null,
    products: ["Diesel", "Renewable Fuel", "Bio-Diesel", "DEF"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 17,
    transports: 25,
    rep: { first: "Nicole", last: "Foster", email: "nfoster@coastal-energy.example.com" },
  },
  {
    slug: "apex-fuel",
    companyName: "Apex Fuel Co.",
    stateInc: "Illinois",
    nationwide: false,
    states: ["Illinois", "Indiana", "Wisconsin", "Iowa", "Missouri"],
    annualGallons: 48_000_000,
    cert: "DBE" as const,
    products: ["Diesel", "Gas", "Premium Gas", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 12,
    transports: 28,
    rep: { first: "Marcus", last: "Ellis", email: "marcus.ellis@apex-fuel.example.com" },
  },
  {
    slug: "skyport-aviation",
    companyName: "Skyport Aviation Fuels",
    stateInc: "Texas",
    nationwide: false,
    states: ["Texas", "Louisiana", "Oklahoma"],
    annualGallons: 31_000_000,
    cert: null,
    products: ["Jet Fuel", "Diesel", "DEF"],
    wetHose: true,
    emergency: "Under 2 hours",
    tankwagons: 8,
    transports: 14,
    rep: { first: "Richard", last: "Avila", email: "ravila@skyport-aviation.example.com" },
  },
  {
    slug: "great-lakes-marine",
    companyName: "Great Lakes Marine Petroleum",
    stateInc: "Wisconsin",
    nationwide: false,
    states: ["Wisconsin", "Michigan", "Minnesota", "Illinois"],
    annualGallons: 22_000_000,
    cert: null,
    products: ["Marine Fuel", "Diesel", "Gas"],
    wetHose: false,
    emergency: "Under 8 hours",
    tankwagons: 9,
    transports: 12,
    rep: { first: "Susan", last: "Kowalski", email: "skowalski@great-lakes-marine.example.com" },
  },
  {
    slug: "greenfield-bio",
    companyName: "Greenfield BioEnergy Supply",
    stateInc: "Iowa",
    nationwide: false,
    states: ["Iowa", "Illinois", "Nebraska", "Minnesota", "Wisconsin"],
    annualGallons: 15_000_000,
    cert: null,
    products: ["Bio-Diesel", "Renewable Fuel", "Diesel", "DEF"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 6,
    transports: 10,
    rep: { first: "Ethan", last: "Wright", email: "ewright@greenfield-bio.example.com" },
  },
  {
    slug: "twin-cities",
    companyName: "Twin Cities Fuel Co.",
    stateInc: "Minnesota",
    nationwide: false,
    states: ["Minnesota", "Wisconsin"],
    annualGallons: 26_000_000,
    cert: null,
    products: ["Diesel", "Gas", "DEF", "Heating Oil"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 11,
    transports: 15,
    rep: { first: "Amy", last: "Johansson", email: "ajohansson@twin-cities-fuel.example.com" },
  },
  {
    slug: "desert-sun",
    companyName: "Desert Sun Petroleum",
    stateInc: "Nevada",
    nationwide: false,
    states: ["Nevada", "Arizona", "California"],
    annualGallons: 18_000_000,
    cert: null,
    products: ["Diesel", "Gas"],
    wetHose: false,
    emergency: "Under 24 hours",
    tankwagons: 7,
    transports: 11,
    rep: { first: "Daniel", last: "Cruz", email: "dcruz@desert-sun-petroleum.example.com" },
  },
  {
    slug: "atlantic-terminal",
    companyName: "Atlantic Terminal Fuels",
    stateInc: "New Jersey",
    nationwide: true,
    states: ["New Jersey", "New York", "Pennsylvania", "Connecticut", "Delaware", "Maryland"],
    annualGallons: 175_000_000,
    cert: null,
    products: ["Diesel", "Gas", "Premium Gas", "Heating Oil", "DEF"],
    wetHose: true,
    emergency: "Under 4 hours",
    tankwagons: 44,
    transports: 58,
    rep: { first: "Paul", last: "Romano", email: "promano@atlantic-terminal.example.com" },
  },
  {
    slug: "ozark-delivery",
    companyName: "Ozark On-Site Fuel Delivery",
    stateInc: "Missouri",
    nationwide: false,
    states: ["Missouri", "Arkansas", "Kansas"],
    annualGallons: 4_800_000,
    cert: null,
    products: ["Diesel", "Gas", "Dyed Diesel"],
    wetHose: true,
    emergency: "Under 2 hours",
    tankwagons: 4,
    transports: 5,
    rep: { first: "Rachel", last: "Morgan", email: "rmorgan@ozark-delivery.example.com" },
  },
] as const

/** Application defs — 15 total; indices 0-3 map to first 4 vendors for approved */
export const APPLICATION_DEFS = [
  { status: "pending_review" as const, companyName: "Ridgeline Fuel Transport", source: "self_applied" as const },
  { status: "pending_review" as const, companyName: "Capitol City Petroleum", source: "invited" as const },
  { status: "pending_review" as const, companyName: "Blue Ridge Energy LLC", source: "self_applied" as const },
  { status: "pending_review" as const, companyName: "Northgate Fuels Inc.", source: "invited" as const },
  { status: "pending_review" as const, companyName: "Trinity Petroleum Services", source: "self_applied" as const },
  { status: "pending_review" as const, companyName: "Lakeshore Fuel Partners", source: "self_applied" as const },
  { status: "pending_review" as const, companyName: "Frontier Oil & Gas Co.", source: "invited" as const },
  { status: "pending_review" as const, companyName: "Summit Ridge Distributors", source: "self_applied" as const },
  { status: "approved" as const, vendorIndex: 22, companyName: "Apex Fuel Co.", source: "invited" as const },
  { status: "approved" as const, vendorIndex: 0, companyName: "Midwest Petroleum Group", source: "invited" as const },
  { status: "approved" as const, vendorIndex: 6, companyName: "Heartland Energy Partners", source: "self_applied" as const },
  { status: "approved" as const, vendorIndex: 9, companyName: "Summit Petroleum LLC", source: "self_applied" as const },
  { status: "info_requested" as const, companyName: "Crossroads Fuel LLC", source: "self_applied" as const },
  { status: "info_requested" as const, companyName: "Valley View Petroleum", source: "invited" as const },
  { status: "rejected" as const, companyName: "QuickFuel Express", source: "self_applied" as const },
]

export const WET_HOSE_CAP = "Wet-hose/Mobile Refueling"
export const TICKET_CAP = "Provide delivery tickets within 24 hours"
export const MONITOR_CAP = "Install Tank Monitors"
